# Use variables in requests
@apiBaseURL = https://jsonplaceholder.typicode.com

###

# you can add a name label for the request like so:
# get all posts
# @name getPosts
GET {{apiBaseURL}}/posts

###

@specificPost = 7

# get a single post
# @name getPost
GET {{apiBaseURL}}/posts/{{specificPost}}

###

# here you can store the title of the getPost req in a var
# then, use it in the createPost req body (ths could be
# an auth token for instance)
@storedPostTitle = {{getPost.response.body.$.title}}

# create a new post with a .env variable
# @name createPost
POST {{apiBaseURL}}/posts
Content-Type: application/json

{
    "title": "{{storedPostTitle}} -- The Stored Title",
    "body": "bar",
    "someSecret": "{{$dotenv FAKE_SECRET}}",
    "userId": 1
}

###

# update a pre-existing post
# @name updatePost
PATCH {{apiBaseURL}}/posts/{{specificPost}}
Content-Type: application/json

{
    "title": "The Lord of the Rings"
}

###

# delete a specific post
# @name deletePost
DELETE {{apiBaseURL}}/posts/{{specificPost}}

###

# filter post by userId query string
GET {{apiBaseURL}}/posts?userId=5
