# Use variables in requests
@apiBaseURL = https://jsonplaceholder.typicode.com

# get all posts
GET {{apiBaseURL}}/posts

###

@specificPost = 7

# get a single post
GET {{apiBaseURL}}/posts/{{specificPost}}

###

# create a new post with a .env variable
POST {{apiBaseURL}}/posts
Content-Type: application/json

{
    "title": "foo",
    "body": "bar",
    "someSecret": "{{$dotenv FAKE_SECRET}}",
    "userId": 1
}

###

# update a pre-existing post
PATCH {{apiBaseURL}}/posts/{{specificPost}}
Content-Type: application/json

{
    "title": "The Lord of the Rings"
}

###

# delete a specific post
DELETE {{apiBaseURL}}/posts/{{specificPost}}
